/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminProtectedRouteRouteImport } from './routes/admin/_protected/route'
import { Route as AdminProtectedIndexRouteImport } from './routes/admin/_protected/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProtectedRouteRoute = AdminProtectedRouteRouteImport.update({
  id: '/admin/_protected',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProtectedIndexRoute = AdminProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminProtectedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminProtectedRouteRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminProtectedIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin': typeof AdminProtectedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/_protected': typeof AdminProtectedRouteRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/_protected/': typeof AdminProtectedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/admin/login' | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin/login' | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin/_protected'
    | '/admin/login'
    | '/admin/_protected/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminProtectedRouteRoute: typeof AdminProtectedRouteRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_protected': {
      id: '/admin/_protected'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_protected/': {
      id: '/admin/_protected/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminProtectedIndexRouteImport
      parentRoute: typeof AdminProtectedRouteRoute
    }
  }
}

interface AdminProtectedRouteRouteChildren {
  AdminProtectedIndexRoute: typeof AdminProtectedIndexRoute
}

const AdminProtectedRouteRouteChildren: AdminProtectedRouteRouteChildren = {
  AdminProtectedIndexRoute: AdminProtectedIndexRoute,
}

const AdminProtectedRouteRouteWithChildren =
  AdminProtectedRouteRoute._addFileChildren(AdminProtectedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminProtectedRouteRoute: AdminProtectedRouteRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
